name: nott-test-oidc
services:
  keycloak:
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    image: quay.io/keycloak/keycloak:23.0.4
    volumes:
      - ./data:/opt/keycloak/data/
    command: start-dev
